// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ZIFhLgrp4h4rWz9TVP_IxkmV0gtDtWA',
    appId: '1:353036121892:web:403a40846225a46b8c25b1',
    messagingSenderId: '353036121892',
    projectId: 'my-app-8etnzk',
    databaseURL: 'https://my-app-8etnzk-default-rtdb.asia-southeast1.firebasedatabase.app/',
    authDomain: 'my-app-8etnzk.firebaseapp.com',
    storageBucket: 'my-app-8etnzk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqT4XciPuaq_-VZoJh9-n3qQWQgJVqyXA',
    appId: '1:353036121892:android:32441285e2227b5e8c25b1',
    messagingSenderId: '353036121892',
    projectId: 'my-app-8etnzk',
    databaseURL: 'https://my-app-8etnzk-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'my-app-8etnzk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyVLA5_QgQYQVSRhLPVOMgyHsc-1nvme0',
    appId: '1:353036121892:ios:fa2d18c417bbe6098c25b1',
    messagingSenderId: '353036121892',
    projectId: 'my-app-8etnzk',
    storageBucket: 'my-app-8etnzk.appspot.com',
    iosClientId: '353036121892-5cgirhg5kifmjo5e1pu4b7gffv3behl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyVLA5_QgQYQVSRhLPVOMgyHsc-1nvme0',
    appId: '1:353036121892:ios:911631c1cb21e1ac8c25b1',
    messagingSenderId: '353036121892',
    projectId: 'my-app-8etnzk',
    storageBucket: 'my-app-8etnzk.appspot.com',
    iosClientId: '353036121892-bj5992i0i73pgsuu103c6ds7aod15egi.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
